fix promoted-content font weight
Financial-Times/o-teaser pull request #120
Opened 2019-03-26 14:49 UTC by SamiTriki

Not sure of whether this way is the most appropriate please feel free to amend.

The promoted label in white text should be bold.

It seems like between o-labels 3 and 4 we had a regression on promoted content labels where the font inherits from the base label style instead of the more specific font-weight that the meta prefix should have. 

Here are screenshots of the problem on native ads

Front page with o-labels `3.x.x`
![](https://puu.sh/D5BSG/d2a91087a8.png)

Stream page with o-labels `4.x.x`
![](https://puu.sh/D5BSU/b361770275.png)

2019-03-26 17:46 UTC, JakeChampion approved these changes

2019-03-26 17:55 UTC, notlee requested changes
Hey, the font-weight [is explicitly set by o-labels v4](https://github.com/Financial-Times/o-labels/blob/d6050d55273002067cd6d4f552d068832bf766c3/src/scss/_mixins.scss#L10). I think the move from a bold font weight is intentional.  @rowanmanning worked on the new version of labels and should be able to confirm.

The screenshot you shared doesn't quiet look like our o-teaser demo. I'm wondering if it's a different problem? Do you have an example I could take a look at in browser?

<img width="383" alt="Screenshot 2019-03-26 at 17 51 16" src="https://user-images.githubusercontent.com/10405691/55020962-d6246c00-4fef-11e9-83e1-e9504fc57212.png">

2019-03-27 10:57 UTC, rowanmanning commented
Yep it looks like the label styles are being overwritten by something in FT.com. @SamiTriki I'm not in the office today, but happy to look at this with you tomorrow.

2019-03-27 11:03 UTC, SamiTriki commented
@notlee You should be able to observe the issue in browser on stream page when a promoted content ad loads, you can see that the font weight is set as 500

Alternatively you can check the component demos in x-dash https://financial-times.github.io/x-dash/components/x-teaser if you scroll to the very bottom and select "paid post"

I don't know if it's a design decision, but even if it is, we have an inconsistency where the front page promoted content prefix are in bold and light on stream pages

2019-03-27 11:03 UTC, SamiTriki commented
@rowanmanning Happy to have a chat with you tomorrow to talk through it

2019-03-27 11:15 UTC, SamiTriki commented
@notlee also the change is explicit in `o-labels` but there's an explicit override in `o-teaser` to bold for teasers meta which include the label text

2019-03-27 11:27 UTC, notlee commented
Hmm I couldn't get find promoted content on a stream page, but looks like the x-dash component is correctly using v4 (with reduced weight, within a bold meta tag):

<img width="365" alt="Screenshot 2019-03-27 at 11 14 29" src="https://user-images.githubusercontent.com/10405691/55071817-87271700-5081-11e9-8643-40685a3cc617.png">

If you'd like to talk through it today instead of tomorrow I'm happy to help also.

2019-03-27 16:25 UTC, SamiTriki commented
After chatting with @notlee the font weight should be 500 as it is currently, no extra change is needed, also o-labels and o-teaser need to be updated on front page.

2019-03-27 16:25 UTC, closed without merging

2019-03-28 10:28 UTC, notlee commented
Thanks Sami! Turns out we were missing a font face, see here: https://github.com/Financial-Times/n-ui-foundations/pull/56